--- 
clone: 
  depth: 1
kind: pipeline
name: Blaster4385Pipeline
steps: 
  - name: submodules
    image: alpine/git
    commands:
     - git submodule init
     - git submodule update
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands:
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/build | bash"
    image: fadlyas/kernel_dockerfile:latest
    name: Build
    trigger: 
      branch: 
        - master
